services:
  - type: web
    name: transmision-multipantalla-backend
    env: node
    buildCommand: npm install && npx prisma generate
    startCommand: npx prisma migrate deploy && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://tu-frontend.vercel.app
    autoDeploy: true
    disk:
      name: data
      mountPath: /data
      sizeGB: 1

databases:
  - name: transmision-multipantalla-db
    databaseName: transmision_multipantalla
    user: admin
